### ISSUE TITLE
关于kotlin-1-基本语法中变量声明有不同意见

### ISSUE THREAD

**Issue by Taonce** [kaixueio/kaixue-docs#3]
[存在不同意见](https://github.com/kaixueio/kaixue-docs/blob/772e1b19a54f6113580928d294e690116b842577/%E6%96%87%E7%AB%A0/Kotlin-1-%E5%9F%BA%E6%9C%AC%E8%AF%AD%E6%B3%95/Kotlin-1-%E5%9F%BA%E6%9C%AC%E8%AF%AD%E6%B3%95.md#1%E5%8F%98%E9%87%8F%E7%9A%84%E5%A3%B0%E6%98%8E)，作者提到`val`和`var`的区别在于是否只能赋值一次，个人愚见，`val`和`var`最主要的区别是在于能否重写`set()`和`get()`方法。`val`是不可重写`set()`方法，只可重写`get()`，而`var`都可重写。

**Comment by XiaMuYao** [comment]
hmm 你和作者说的其实是一个意思，或许我换句话表达可以满足你们的想法
var 可变变量：随时可变
val 只读变量：只能在初始化时改变。

**Comment by CnPeng** [comment]
感谢提出异议。

个人认为：

- set/get的最终目的是为了取值和赋值。
- val 不能重写 set() 从表象来看，就是只能一次赋值，

**Comment by Taonce** [comment]
@CnPeng 非常感谢，我的疑惑解开了
